window.APP_CONFIG = {
  APP_VERSION: "5.2.1",
  SUPABASE_URL: "https://sbfpcsdnpnjbjvorydpr.supabase.co",
  SUPABASE_PUBLISHABLE_KEY: "sb_publishable_VGX2Wnp1KGMYwLtYTM-Gbw_6fosyXfC",
  DEFAULT_FIELD_DURATION_MINUTES: 60,
  OPENING_HOUR: 9,
  PAID_FROM_HOUR: 19,
  CLOSING_HOUR: 22,
  CONTACT_PHONE_DISPLAY: "328 673 9425",
  CONTACT_PHONE_LINK: "+393286739425",
  WEATHER_LOCATION_NAME: "Bologna – Campo Don Orione",
  WEATHER_LATITUDE: 44.4949,
  WEATHER_LONGITUDE: 11.3426,
  WEATHER_TIMEZONE: "Europe/Rome"
};
